spring:
  application:
    name: hystrix-dashboard-service
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka  